.PHONY: lint
lint:
	go fmt ./...
	go run github.com/daixiang0/gci@master write -s standard -s default -s "prefix(github.com/fpetkovski/tscodec-go)" .
	go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...

.PHONY: test
test:
	go test ./...